[theme]

# Primary accent for interactive elements
primaryColor = '#F5EFE6'

# Background color for the main content area
# I'm opting for a milktea color because I like milktea
backgroundColor = '#EDDBC0'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#9F8772'

# Color used for almost all text
textColor = '#594545'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"
font-size = 1.5